In [1]:
#1 Створити функцію яка приймає на вхід два масива типу ndarray та повертає масив сума елементів якого найбільша. 

import numpy as np

arr1 = np.array([1,2,3,4,0, 100])
arr2 = np.array([2,2,35,4,8])

def get_biggest_array(arr1, arr2):
    if np.sum(arr1) > np.sum(arr2):
        return arr1
    else:
        return arr2

print( get_biggest_array(arr1, arr2) )

[  1   2   3   4   0 100]


In [2]:
#2 Створити функцію яка приймає на вхід масив типу ndarray та повертає суму його унікальних елементів. 
import numpy as np

arr = np.array([1,2,3,4,9,9,4,10,-6])

def sum_of_unique(arr):
    output = np.unique(arr)
    return np.sum(output)

print( sum_of_unique(arr) )

23


In [4]:
#3 Створити функцію яка приймає на вхід одновимірний масив типу ndarray, змінює його форму на 3х3 та повертає результат. 
# Додатково: спробуйте в самій функції реалізувати перевірку розміру вхідного масиву, так щоб переконатись що його форму можна привести до 3х3
# Назва функції повинна бути як і в прикладі та сама функція повинна повертати ту ж кількість параметрів того же типу який зазначений нижче
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9])

def reshape_array(arr):
    if np.size(arr) == 9:
        arr.shape = (3, 3)    
        return arr   
    else:
        return "Got not valid array"
    
   

print( reshape_array(arr))


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#4 Створити функцію яка приймає на вхід одновимірний масив типу ndarray, розбиває його на 5 бінів та повертає масив з кількістю елементів в кожному біні. 

arr = np.array([1,2,3,4,5,6,7,8,90])

def get_frequency(arr):
    result = np.histogram(arr, bins=5)
    #print(result[1])
    return result[0]

print( get_frequency(arr))

[8 0 0 0 1]


In [6]:
#5 Створити функцію яка приймає на вхід масив ndarray квадратної форми, та повертає його перший стовбець. 

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

def get_first_column(arr):

    if arr.shape[0] != arr.shape[1]:
        return "Масив має бути квадратним"

    return arr[:, 0]

print( get_first_column(arr) )

[1 4 7]


In [7]:
#6 Створити функцію яка приймає на вхід масив ndarray квадратної форми, та повертає два перші рядки масиву

arr = np.array([[1,2,3,1],[4,5,6,6],[7,8,9,9],[0,0,0,0]])

def get_two_first_rows(arr):

    if arr.shape[0] != arr.shape[1]:
        return "Масив має бути квадратним"

    return arr[0:2, :]

print( get_two_first_rows(arr) )

[[1 2 3 1]
 [4 5 6 6]]


In [8]:
#7 Створити функцію яка приймає на вхід два масива ndarray квадратної форми, та повертає їх різницю

arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2 = np.array([[2,3,0],[7,5,9],[1,9,0]])

def arrays_substract(arr1, arr2):
    return np.subtract(arr1, arr2)

print(arrays_substract(arr1, arr2))


[[-1 -1  3]
 [-3  0 -3]
 [ 6 -1  9]]


In [9]:
#8 Створити функцію яка приймає на вхід масив ndarray квадратної форми, та повертає його елементи які більше 2

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

def get_greater_the_two(arr):
    #arr = arr[arr>2]
    return arr[arr>2]

print( get_greater_the_two(arr) )

[3 4 5 6 7 8 9]


In [10]:
#9 Створити функцію яка приймає на вхід масив ndarray квадратної форми, та повертає всі його від'ємні елементи

arr = np.array([[-1,2,3],[-4,5,-6],[7,8,-9]])

def get_negative_elements(arr):
    #arr = arr[arr<0]
    return arr[arr<0]

print( get_negative_elements(arr))

[-1 -4 -6 -9]


In [11]:
#10 Створити функцію яка приймає на вхід масив ndarray квадратної форми, міняє місцями два перші його стовбці, та повертає нову версію масиву(уже зі зміненним порядком стовбців)

arr = np.array([[0,2,3],[4,5,6],[7,8,9]])

def swap_columns(arr):
    #arr = arr[:,[1,0,2]]
    return arr[:,[1,0,2]]

print( swap_columns(arr))

[[2 0 3]
 [5 4 6]
 [8 7 9]]


In [12]:
#11 Створити функцію яка приймає на вхід масив ndarray квадратної форми, транспонує його, знаходить обернену матрицю та повертає даний результат

arr = np.array([[1,2,1],[4,5,6],[7,8,9]])

def traspose_and_get_inv(arr):
    arr = np.transpose(arr)
    return np.linalg.inv(arr)

print( traspose_and_get_inv(arr))

[[-0.5         1.         -0.5       ]
 [-1.66666667  0.33333333  1.        ]
 [ 1.16666667 -0.33333333 -0.5       ]]


In [13]:
#12 Створити функцію яка приймає на вхід масив ndarray квадратної форми, та сортує його по axis=0(першій осі)

arr = np.array([[3,2,5],[9,1,36],[17,88,19]])

def sort_by_first_axis(arr):
    
    arr = np.sort(arr, axis=0)
    
    return arr

print( sort_by_first_axis(arr))

[[ 3  1  5]
 [ 9  2 19]
 [17 88 36]]


In [14]:
#13 Створити функцію яка приймає на вхід масив ndarray квадратної форми, та заміняє в ньому всі значення nan на нулі, після чого повертає його оновлену версію

arr = np.array([[3,np.nan,5],[np.nan,1,2],[np.nan,3,np.nan]])

def replace_nan_on_zero(arr):
    temp_arr = np.isnan(arr)
    arr = np.where( temp_arr, 0, arr)
    return arr
    
print(replace_nan_on_zero(arr))

[[3. 0. 5.]
 [0. 1. 2.]
 [0. 3. 0.]]


In [15]:
#14 Створити функцію яка приймає на вхід масив ndarray квадратної форми, підносить його до степеню 3 та множить результуючий масив на 2, після чого повертає результат

arr = np.array([[2,2,5],[9,1,36],[17,88,19]])

def calculate_array(arr):
    return (arr**3)*2

print( calculate_array(arr))

[[     16      16     250]
 [   1458       2   93312]
 [   9826 1362944   13718]]


In [16]:
#15 Створити функцію яка приймає на вхід масив ndarray квадратної форми, збільшує його розмірність на 1 по першій осі та повертає результат

arr = np.array([[3,2,5],[9,1,36],[17,88,19]])

def increase_ndim(arr):
    arr = np.expand_dims(arr, axis = 0)
    #print(arr[0, 1,2])
    return arr

print( increase_ndim(arr))

[[[ 3  2  5]
  [ 9  1 36]
  [17 88 19]]]
